services:
  app:
    image: php:8.3-fpm
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:stable
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: laravel-db
    environment:
      POSTGRES_DB: espeletia
      POSTGRES_USER: espeletia
      POSTGRES_PASSWORD: espeletia
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
